### ISSUE TITLE
 folder for policies

### ISSUE THREAD

**Issue by lbombonatoinsped** [GoogleChromeLabs/chrome-for-testing#106]
in version 115 the folder for policies in Linux was `/etc/chromium/policies/managed/`

What is the folder in the current version?

I tried 
```
/etc/opt/chromium/policies/managed/
/etc/chromium/policies/managed/
/etc/opt/chrome/policies/managed/
/etc/chrome/policies/managed/
```
but the policy does not appear in `chrome://policy/`

**Comment by OrKoN** [comment]
They should be in ‘chrome_for_testing’ folder according to https://chromium.googlesource.com/chromium/src/+/HEAD/docs/enterprise/policies.md

**Comment by lbombonatoinsped** [comment]
It worked! thank you very much
