### ISSUE TITLE
chromedriver version not found

### ISSUE THREAD

**Issue by cheshennull** [GoogleChromeLabs/chrome-for-testing#116]
My chrome version is 122.0.6261.95, but I did not find the download link for chromedriver 122.0.6261.95, only 122.0.6261.94. The version is inconsistent, causing it to crash when I use selenium to call it.

**Comment by mathiasbynens** [comment]
`122.0.6261.95` is not in [`known-good-versions.json`](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions.json).

Following https://developer.chrome.com/docs/chromedriver/downloads/version-selection, you’d then check [`LATEST_RELEASE_122.0.6261`](https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_122.0.6261) which gives you the compatible ChromeDriver version to use: `122.0.6261.94`

**Comment by dmurdoch** [comment]
This seems to have happened again, but the advice from @mathiasbynens isn't working.  On MacOS-x64, Chrome has recently updated to 123.0.6312.59.  The corresponding latest release link says to use 123.0.6312.58, but that version doesn't work for me.

**Comment by OrKoN** [comment]
The latest stable build available everywhere is 123.0.6312.58. https://chromiumdash.appspot.com/releases?platform=Mac .59 is still 50%/50% roll-out and it is not available on all platforms.

https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.58/mac-x64/chromedriver-mac-x64.zip seems to work fine.

**Comment by dmurdoch** [comment]
Thanks.  I think this is something else:  I installed Chrome for Testing 123.0.6312.58, and have the same issue, which is that Selenium is giving a status 500 response to the request to open.  I'm using R and getting to Selenium through RSelenium, so the error is likely in one of those.
