### ISSUE TITLE
When activated with headless=new mode, elements that can be retrieved with headfull cannot be retrieved.

### ISSUE THREAD

**Issue by kazuya-saeki** [GoogleChromeLabs/chrome-for-testing#117]
Hi,

When 116.0.5793.0 was first released, headfull and headless worked exactly the same, and there was no failure of either alone, as expected. However, in the transition releases, headless has been failing more and more often (mainly due to element not being retrieved or render timeout), and now they are working completely differently.

If anyone has any ideas or remedies, please let us know...

**Comment by mathiasbynens** [comment]
Do you have a repro? If so, please report this at https://goo.gle/headless-bug.
