### ISSUE TITLE
folder for policies on windows

### ISSUE THREAD

**Issue by maiargu** [GoogleChromeLabs/chrome-for-testing#118]
Related to the same question for linux system https://github.com/GoogleChromeLabs/chrome-for-testing/issues/106

When I'm on a windows machine and install chrome-for-testing via command `npx puppeteer browsers install chrome`
A folder is created where all the source files are downloaded.

![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/92865676/07a17d96-5b01-4dd8-b7a0-47cbce1bba2d)

Where exactly there, in the folder, in which file, and in which format should I place my policies so that I can see them when chrome-for-testing `chrome.exe` is started and I type in the browser the url `chrome://policy/` ?

**Comment by maiargu** [comment]
Not really, or I misunderstand here something.

The documentation mentions that under windows `the Policies can be set up via Windows Registry`.

But when I do this in my Windows Registry, it seems that these are the policies for my local Google Chrome installation
(I can see them as properly configured in a browser tab when typing the url `chrome://policy/` ).

![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/92865676/ea695c01-20f3-48a6-83c9-91a892af398b)


But the policies configured in my registry are not the policies that are considered when I start the `chrome.exe` chrome-for-testing from the folder

`.cache/puppeteer/chrome/win64-122.0.6261.69/chrome-win64`

This is why my assumption was that for chrome-for-testing the policies have to be placed somewhere in the folder `.cache/puppeteer/chrome/win64-122.0.6261.69/chrome-win64` ?

Would appreciate any guidance here.

**Comment by mathiasbynens** [comment]
Ah, I see. This was recently changed.

https://chromium-review.googlesource.com/c/chromium/src/+/5315959 (landed in M124) changed the policy path CfT uses on Windows to `SOFTWARE\Policies\Google\Chrome for Testing`. Older versions (like M122 in your example) still use the same path as Chromium.

**Comment by mathiasbynens** [comment]
Ah, I see. This was recently changed.

https://chromium-review.googlesource.com/c/chromium/src/+/5315959 (landed in M124) changed the policy path CfT uses on Windows to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome for Testing`. Older versions (like M122 in your example) still use the same path as Chromium.

**Comment by maiargu** [comment]
Thanks for you answer!

I tried and configured the registry `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome for Testing`

But when I start the `chrome.exe` chrome-for-testing from the folder `.cache/puppeteer/chrome/win64-122.0.6261.69/chrome-win64` the configured policies in the above mentioned registry are still not considered.

**Comment by mathiasbynens** [comment]
As I mentioned, the path change landed in Chrome 124. Older versions (like M122 in your example) still use the same path as Chromium.

**Comment by maiargu** [comment]
Ah, yes, I can confirm.

With chrome-for-testing v.124 and registry path `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome for Testing` everything works like a charm :)

Thanks for the support!
