### ISSUE TITLE
Where is Chrome 124 in stable?

### ISSUE THREAD

**Issue by alexsch01** [GoogleChromeLabs/chrome-for-testing#122]

**Comment by Lorondos** [comment]
Same please, our agents have updated to Chrome 124 yet there is no stable 124 chrome driver so we are looking to rollback.

**Comment by OrKoN** [comment]
So actually it looks like it is already available on Linux, Windows and Mac:

```
npx @puppeteer/browsers install chromedriver@124
```

Not sure why dashboard is lagging, maybe it is waiting for the latest 123 release to clear first. cc @mathiasbynens

**Comment by madonix994** [comment]
Same issue here. Do we have a solution for this? When it will be available for selenium manager?
I am having issue that Chrome is not terminating process and CPU workload is constant 100% since it is using selenium java 4.19.1 with manager with usage of CDP 123.

Kind regards.

**Comment by Shahzodjohn** [comment]
Extremely needed chromedriver version 124. Can we have release dates?

**Comment by Lorondos** [comment]
It is currently released but the dashboard is lagging:

https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone-with-downloads.json

https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.60/win32/chrome-win32.zip

**Comment by mathiasbynens** [comment]
The CfT 124 downloads that are available are builds from other channels.

The dashboard isn’t lagging, it’s just that [124 is not yet 100% Stable.](https://chromiumdash.appspot.com/releases).

If you need ChromeDriver 124 now, you can follow [the same guidance as always](https://developer.chrome.com/docs/chromedriver/downloads/version-selection#for_versions_115_and_newer). E.g.

```
$ curl https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_124
124.0.6367.60
```

**Comment by Shahzodjohn** [comment]
> The CfT 124 downloads that are available are builds from other channels.
> 
> The dashboard isn’t lagging, it’s just that [124 is not yet 100% Stable](https://chromiumdash.appspot.com/releases), and so our dashboard + API doesn’t mark it as Stable yet.
> 
> If you need ChromeDriver 124 now, you can follow [the same guidance as always](https://developer.chrome.com/docs/chromedriver/downloads/version-selection#for_versions_115_and_newer). E.g.
> 
> ```
> $ curl https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_124
> 124.0.6367.60
> ```

but i need a phisical file of chromeDriver version 124

**Comment by mathiasbynens** [comment]
> but i need a phisical file of chromeDriver version 124

Please give [the guidance I pointed to](https://developer.chrome.com/docs/chromedriver/downloads/version-selection#for_versions_115_and_newer) a try.

**Comment by Shahzodjohn** [comment]
i see only old versions there


> The CfT 124 downloads that are available are builds from other channels.
> 
> The dashboard isn’t lagging, it’s just that [124 is not yet 100% Stable](https://chromiumdash.appspot.com/releases), and so our dashboard + API doesn’t mark it as Stable yet.
> 
> If you need ChromeDriver 124 now, you can follow [the same guidance as always](https://developer.chrome.com/docs/chromedriver/downloads/version-selection#for_versions_115_and_newer). E.g.
> 
> ```
> $ curl https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_124
> 124.0.6367.60
> ```

**Comment by Shahzodjohn** [comment]
![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/77686662/4ab5cb22-fa5f-441b-99cd-4c5e60bf00fa)
 Here is a screen shot. The current  folder is empty but if  i open a parrent folder. There is a latest chrome Driver version 114 it is not the version i want :(

**Comment by mathiasbynens** [comment]
What page is that? That looks like an open directory listing, which we don’t provide for CfT. I think you’re looking at another web page.

**Comment by Shahzodjohn** [comment]
Can you please send a direct url using which gives me a chromedriver file? Here is my chrome browser version 124.0.6367.61

**Comment by larissafiorini** [comment]
https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.60/win64/chromedriver-win64.zip

**Comment by alexsch01** [comment]
I made https://alexsch01.github.io/chrome-for-testing/ which is a nice GUI on top of the Chrome for Testing API

**Comment by muraliagreeya** [comment]
Getting below exception when trying to latest Google chrome and chromedriver of 124 version 
Please share 124 Devtools maven dependency.

Exception : java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'

Using 123 DevTools in POM file
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-devtools-v123</artifactId>
    <version>4.19.1</version>
</dependency>

**Comment by dmidura** [comment]
I am seeing this CPU load issue. I am on chromedriver 124.0.6367.79
I am using selenium-java 4.20.0 (just released).
My machine is spinning the CPU out of control. What is the resolution?

**Comment by Rohithssyr** [comment]
> I am seeing this CPU load issue. I am on chromedriver 124.0.6367.79 I am using selenium-java 4.20.0 (just released). My machine is spinning the CPU out of control. What is the resolution?

Even we faced same[Unable to kill the process], just rollback to previous version for now till it get fixed

**Comment by ravikiranreddy6295** [comment]
When this problem will be fixed? 
I am still not able to kill the chrome?
When I run the test cases CPU utilisation is 100% and system is getting stuck.

**Comment by oomeravcii** [comment]
> https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.60/win64/chromedriver-win64.zip

I was looking for this, thanks!
