### ISSUE TITLE
CPU load issue with chromedriver 124.0.6367.79

### ISSUE THREAD

**Issue by dmidura** [GoogleChromeLabs/chrome-for-testing#126]
I am seeing very high CPU usage when running automation. I am on chromedriver 124.0.6367.79
I am using selenium-java 4.20.0 (just released) which includes support for CDP 124. 
Can someone please tell me how to reduce the CPU load clocking for my automation?

[_Originally posted by @dmidura in https://github.com/GoogleChromeLabs/chrome-for-testing/issues/122#issuecomment-2076111078_](https://github.com/GoogleChromeLabs/chrome-for-testing/issues/122#issuecomment-2066268689)

**Comment by OrKoN** [comment]
Please report the issue to the chromedriver tracker https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by diemol** [comment]
This has been reported a couple of days ago: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4744

**Comment by ysiivan** [comment]
> This has been reported a couple of days ago: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4744

While it could be related, the quoted entry is for v123, not 124.
I had no problem with v123, but v124 leaves orphaned chrome processes with high cpu usage.

**Comment by doctorsketch** [comment]
I've had this issue in Windows, I've also been using a Linux VM and that has never had this issue. I've been hit by this quite badly as I only have 2 cores on my CPU which lock up as soon as I have 2 zombie threads. I've been using this as a workaround:

`import psutil

def kill_driver(driver):
    """Forcefully kills the WebDriver and all its child processes."""
    try:
        driver.quit()  # Attempt to quit the driver cleanly.
    except Exception as e:
        print(f"Failed to quit the driver cleanly: {e}")

    try:
        parent_pid = driver.service.process.pid
        if psutil.pid_exists(parent_pid):  # Check if the process still exists
            parent = psutil.Process(parent_pid)
            for child in parent.children(recursive=True):  # Kill all child processes
                if child.is_running():
                    child.kill()
            if parent.is_running():  # Check again before killing
                parent.kill()
    except psutil.NoSuchProcess:
        print("No such process; it was already terminated.")
    except Exception as e:
        print(f"An error occurred while trying to kill the process: {e}")
`

use kill_driver(driver) instead of driver.quit()

Not great, but it'll do until this is fixed properly.

**Comment by balivadas** [comment]
This problem can be resolved by removing "--no-sandbox" args from chrome options if you are using it.
