### ISSUE TITLE
Target is getting auto attached to an empty  target after upgrading chrome driver to 124

### ISSUE THREAD

**Issue by manish-mn** [GoogleChromeLabs/chrome-for-testing#133]
Hi i am using appium to automate android apps where i have to switch to webview as the app is hybrid.
Its unable to switch webview because the target the getting attached automatically to the empty target.
I have checked it on chromedriver 99 and it works fine.
Logs -
https://gist.github.com/manish-mn/c09cbae77f8adbb9d8618c5723daf0a0

**Comment by mathiasbynens** [comment]
> [!IMPORTANT]
**This issue tracker tracks bugs with [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/) and [its API](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).**
> 
> - Are you reporting a bug that reproduces in Chrome for Testing but not in Chrome? File it here: https://goo.gle/cftbug
> - Are you reporting a bug in Chrome? File it here: https://crbug.com/new
