### ISSUE TITLE
Latest version 125.0.6422.78 not available at dl.google.com

### ISSUE THREAD

**Issue by ani-shk** [GoogleChromeLabs/chrome-for-testing#136]
We have a script that downloads the latest rpm version of google chrome on our jenkins pipelines.
Since the version `125.0.6422.78`, we are unable to download it from [here](https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-125.0.6422.78-1.x86_64.rpm) 

I hope this is the right place to report the issue 🤞🏽

**Comment by OrKoN** [comment]
Nope, unfortunately, the issue needs to be reported through other channels (perhaps https://crbug.com ?) as the endpoint you use is not for Chrome for Testing but for regular Chrome. Do you know where this endpoint is documented? Perhaps there is a contact channel there.

**Comment by pluralistix** [comment]
🤔 Is there - anyway - an explanation, why there is a 125.0.6422.78 "here"? From chrom(e|ium) side, there only has been .76 (22/05/2024) and now .112 (24/05/2024) in the stable channel.

**Comment by StuartDewar** [comment]
> 🤔 Is there - anyway - an explanation, why there is a 125.0.6422.78 "here"? From chrom(e|ium) side, there only has been .76 (22/05/2024) and now .112 (24/05/2024) in the stable channel.

Yeah i'm intrigued by this too. 

My team are having the exact issue reported by @ani-shk. Ubuntu Updates shows .76 then a jump to .112 - https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable

It's a bit confusing as to where .78 has came from.

**Comment by OrKoN** [comment]
You can see all releases here https://chromiumdash.appspot.com/releases?platform=Mac (change the platform to see a platform-specific view)

**Comment by Stoooart** [comment]
> You can see all releases here https://chromiumdash.appspot.com/releases?platform=Mac (change the platform to see a platform-specific view)

There's no `125.0.6422.78` for Linux in that dashboard?

**Comment by OrKoN** [comment]
That's right, but it exists for, e.g., Mac and Chrome for Testing gets the same version published for all platforms.

**Comment by Stoooart** [comment]
> That's right, but it exists for, e.g., Mac and Chrome for Testing gets the same version published for all platforms.

Except it didn't get published for Linux? 

I'm hoping that next time a version bump rolls round this issue just solves itself and Linux has consistent versions with Chrome & ChromeDriver again - for now i'm just hard-coding to .112.

**Comment by OrKoN** [comment]
<img width="1354" alt="Screenshot 2024-05-29 at 11 28 11" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/399150/5ebac704-0eed-4eb4-936c-1609992afa99">

I see .78 for all platforms. Note that Chrome for Testing is managed differently from that PPA. Chrome for Testing does not include .112 yet.

**Comment by ani-shk** [comment]
Hey @OrKoN , would it be safe to assume that the latest version available on https://chromiumdash.appspot.com/releases?platform=Linux will have a corresponding ChromeDriver available at https://storage.googleapis.com/chrome-for-testing-public/ ?

We ran into similar issue once again, and I was thinking of getting the actual chrome version using the URL https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions/all/releases?filter=endtime%3Dnone and then fetching the chrome driver version using the chrome version.
