### ISSUE TITLE
chrome driver is not available for Version 127.0.6533.73

### ISSUE THREAD

**Issue by 7r5** [GoogleChromeLabs/chrome-for-testing#144]
I have a project that uses latest chrome version and webDriverManager to get the corresponding driver, today chrome got updated to 127.0.6533.73 but I don't see that specific version in the availability table, closest one is 127.0.6533.72

**Comment by sophiste** [comment]
done

**Comment by Hao25725** [comment]
Same Question

**Comment by mathiasbynens** [comment]
Please follow the steps at https://developer.chrome.com/docs/chromedriver/downloads/version-selection.

`127.0.6533.73` does not appear in https://googlechromelabs.github.io/chrome-for-testing/known-good-versions.json, but https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_127.0.6533 indicates that 127.0.6533.119 is compatible:

```
$ curl https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_127.0.6533
127.0.6533.119
```
