### ISSUE TITLE
Timeout error in version 130.0.6723.69

### ISSUE THREAD

**Issue by davisonv** [GoogleChromeLabs/chrome-for-testing#158]
We have updated the driver in our project, current version is 130.0.6723.69, same as chrome, since we've updated a error is beeing thrown: 
`Message: timeout: Timed out receiving message from renderer: 600.000 (Session info: chrome=130.0.6723.69)`

please this parte of  the dockerfile code:
```
RUN apt-get install -y google-chrome-stable

RUN apt-get install -yqq unzip

RUN wget -O /tmp/chromedriver.zip http://storage.googleapis.com/chrome-for-testing-public/$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json | jq -r '.channels.Stable.version')/linux64/chromedriver-linux64.zip

RUN unzip /tmp/chromedriver.zip chromedriver-linux64/chromedriver -d /usr/local/bin/ && mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/ && rmdir /usr/local/bin/chromedriver-linux64
```

**Comment by mathiasbynens** [comment]
> [!IMPORTANT]
**This issue tracker tracks bugs with [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/) and [its API](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).**
> 
> - Are you reporting a bug that reproduces in Chrome for Testing but not in Chrome? File it here: https://goo.gle/cftbug
> - Are you reporting a bug in Chrome? File it here: https://crbug.com/new
