### ISSUE TITLE
Create "chromium-for-testing" default user configuration folder on Linux; note to use --user-data-dir

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/chrome-for-testing#17]
I already had Chromium Version 116.0.5825.0 (Developer Build) (64-bit) from https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots (https://github.com/beaufortfrancois/download-chromium/) running. Downloaded Google Chrome for Testing Version 116.0.5817.0 (Official Build) (64-bit) and launched. 

Since this is built using Chromium, a new instance of Chromium was launched, using the same default configuration folder on Linux, Xubuntu distribution, `~/.config/chromium`.

I think you need to make sure this is creating a "chromium-for-testing" default user configuration folder, just like if we install Chrome proper the first time we launch the folder "google-chrome-unstable" is created in `~/.config`, and so forth for each version.

In the mean time it would be helpful to write conspicuous notices in your blog posts, et al. that the user should launch with `--user-data-dir` flag to avoid the case where launching Chrome for Testing executable will just launch a new Tab in an open Chromium instance when `--user-data-dir` flag is not set. I'm rather sure that is not what you are trying to do here.

**Comment by mathiasbynens** [comment]
I appreciate this report, but it’s not an issue with the code in this repository (which concerns the dashboard and JSON API only). Please file it here instead: https://goo.gle/cftbug

**Comment by mathiasbynens** [comment]
**Update:** I’ve filed it there now: https://bugs.chromium.org/p/chromium/issues/detail?id=1454365
