### ISSUE TITLE
Hardware and OS independent rendering

### ISSUE THREAD

**Issue by Klaster1** [GoogleChromeLabs/chrome-for-testing#19]
When performing visual regression testing, minute rendering differences caused by hardware and OS choice complicate the task so much as to make it unviable without relying on complex solutions, like browser pools (on-premise or SaaS). The current crop of visual comparison algorithms doesn't completely solve the issue either. Is stable cross-platform rendering a goal of the Chrome for Testing project?

**Comment by mathiasbynens** [comment]
> Is stable cross-platform rendering a goal of the Chrome for Testing project?

No.
