### ISSUE TITLE
Any plans to support lower versions of Chrome?

### ISSUE THREAD

**Issue by jiwon-mun** [GoogleChromeLabs/chrome-for-testing#20]
hello!

I was very happy to read the Chrome release documentation ,because it seemed to have the stuff I needed.

However, it seems that only the latest version (113 or higher) is still supported.

It would be better if it supported all versions of Chrome (eg version 60).

Do you have any plans to apply?

**Comment by mathiasbynens** [comment]
Unfortunately it’s not feasible to retroactively make older versions available. Chrome for Testing is available for M113 and later.

**Comment by jiwon-mun** [comment]
This is sad news.

But thank you for always working hard to make Chrome better :)

**Comment by mathiasbynens** [comment]
I’ve now explicitly listed the oldest available version in the README in this commit: 3a040f4588bb3da815b06b463cd2350a5b722e5f
