### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by Tobias43** [GoogleChromeLabs/chrome-for-testing#21]
This repository contains an Apache 2.0 LICENSE file.

Does this mean that only the code in this repository is under the Apache 2.0 license, or also the whole Chrome for Testing?

Or more concretely: Can Chrome for Testing be redistributed as part of a commercial software that uses it for some automation.

**Comment by mathiasbynens** [comment]
The license applies to the code in this repository.

**Comment by mathiasbynens** [comment]
The license at https://github.com/GoogleChromeLabs/chrome-for-testing/blob/main/LICENSE applies to the code in this repository.

To see license information for the Chrome for Testing binary itself, run it with the `--credits` command-line flag.

**Comment by mathiasbynens** [comment]
The license at https://github.com/GoogleChromeLabs/chrome-for-testing/blob/main/LICENSE applies to the code in this repository.

**Comment by Tobias43** [comment]
So which license applies to the Chrome for Testing binary?

**Comment by mathiasbynens** [comment]
> So which license applies to the Chrome for Testing binary?

Chrome for Testing is a flavor of Google Chrome, so https://www.google.com/chrome/terms/ applies.

**Comment by Tobias43** [comment]
Ok, so unfortunately no redistribution is possible. Thank you very much for the quick reply!
