### ISSUE TITLE
ChromeDriver version is missing for Chrome 114.0.5735.198

### ISSUE THREAD

**Issue by valfirst** [GoogleChromeLabs/chrome-for-testing#27]
https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json / https://github.com/GoogleChromeLabs/chrome-for-testing/blob/main/data/known-good-versions-with-downloads.json doesn't contain entry for Chrome browser of version 114.0.5735.198.

This version is used by GH Actions runners: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#browsers-and-drivers

**Comment by OrKoN** [comment]
ChromeDriver downloads are only available since v115.0.5763.0 (see https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints)
