### ISSUE TITLE
Driver Release Notes

### ISSUE THREAD

**Issue by titusfortner** [GoogleChromeLabs/chrome-for-testing#28]
Previous chromedriver releases included a `notes.txt` file listing which issues were addressed from previous version. Is this information accessible somewhere else now? Thanks!

**Comment by thiagowfx** [comment]
Non-authoritative answer: This is a good starting point: https://bugs.chromium.org/p/chromium/issues/list?q=component%3ATest%3EWebDriver%20-is%3Aopen&can=1

**Comment by thiagowfx** [comment]
cc @nechaev-chromium

**Comment by mathiasbynens** [comment]
From [the announced changes](https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE):

> We’ll no longer provide manually curated release notes.
>
> Instead, view the commit history in your local Chromium checkout via `git log chromium/src/chrome/test/chromedriver` or online via <https://github.com/chromium/chromium/commits/main/chrome/test/chromedriver>.
