### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by soulgalore** [GoogleChromeLabs/chrome-for-testing#31]
Hi, with the new way of publishing Chromedriver, is there a way to find the release notes for each release (before it was linked from the release page https://chromedriver.storage.googleapis.com/113.0.5672.63/notes.txt)

**Comment by mathiasbynens** [comment]
From [the announced changes](https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE):

> We’ll no longer provide manually curated release notes.
>
> Instead, view the commit history in your local Chromium checkout via `git log chromium/src/chrome/test/chromedriver` or online via <https://github.com/chromium/chromium/commits/main/chrome/test/chromedriver>.
