### ISSUE TITLE
Chrome 115 HTTPS requirement for downloads

### ISSUE THREAD

**Issue by ngan** [GoogleChromeLabs/chrome-for-testing#34]
As of Chrome (for Testing) 115, we're seeing this error in the logs for test suite:

`http://redacted-url.com:9400/companies/72dcc448-b266-4576-b85c-4b1a5808461b/reports/foobar - The file at 'http://redacted-url.com:9400/system/reports/complete_reports/reports/000/000/014/original/gibson-and-sons-agency-payments-2023-07-2520230725-96772-bdllzx.csv' was loaded over an insecure connection. This file should be served over HTTPS.`

Looks like this was a security update that was released with Chrome 115 (we weren't seeing this in 114). We've tried both Chrome and Chrome for Testing. I get what the error is saying but since this is a CI/testing environment, our server is running in HTTP. Is there a command line argument to disable this check?

Or is the desired outcome for all test environments to now be served over HTTPS with a fake, but allow-listed, SSL certificate?

**Comment by thiagowfx** [comment]
CL: https://chromium-review.googlesource.com/c/chromium/src/+/4535335

**Comment by mathiasbynens** [comment]
Based on the description this is a change that applies to (regular) Chrome, and not an issue that’s specific to Chrome for Testing. To file a Chrome bug, use https://crbug.com/new.
