### ISSUE TITLE
Stable 115.0.5790.110 in last-known-good-versions.json

### ISSUE THREAD

**Issue by alexsch01** [GoogleChromeLabs/chrome-for-testing#35]
When will 115.0.5790.110 be listed in last-known-good-versions.json?

**Comment by OrKoN** [comment]
It should be available there, once, binaries for all platforms are published (currently, missing win64). See https://googlechromelabs.github.io/chrome-for-testing/

**Comment by snydergd** [comment]
@OrKoN I feel like I just didn't read something I should have, but could you explain why this was closed as not planned?  I still don't see it listed in that file and the download link I would expect doesn't seem to work.  Are some Chrome release not made available in chrome-for-testing?

**Comment by OrKoN** [comment]
@snydergd only the releases available across all platforms would be listed in last-known-good-versions.json It does not look like this ended up being the case for 115.0.5790.110 as I suspect it was a windows only variation build. You can cross-check the releases here https://chromiumdash.appspot.com/releases?platform=Mac

**Comment by snydergd** [comment]
@OrKoN In my case I came across this because I was running on Windows where release 115.0.5790.110 was installed, and I tried downloading that version of the webdriver (for Windows), but it seems like it's not out there.  So does this mean that chrome-for-testing doesn't contain chrome releases at all unless they are available for all platforms?  I suppose that makes sense, but just haven't found it explicitly called out anywhere yet.

**Comment by OrKoN** [comment]
I believe it's called out here: https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints (see "all CfT assets")

**Comment by snydergd** [comment]
I think I might be dense but I'm still not seeing it called out there.  The way I read the "matrix" statement after the table, is that chrome and chromedriver are both supported on all the listed platforms, but that doesn't say anything about which release versions are available for each combination.

The descriptions for a few endpoints also talk about referencing versions for which all assets are available - so those endpoints at least wouldn't reference the windows-only release.  The endpoints show "good" and "latest" releases, but I can't tell if other releases should still be available or not (e.g., for 115.0.5790.110).

**Comment by OrKoN** [comment]
@snydergd it says it in the endpoint descriptions that endpoints contain versions "for which **all** CfT assets" are available. That means if there are some platforms that don't have a CfT build for a given version, the version will not be in the list. That is if 115.0.5790.110 is not in the json file, it means it is not available for some platforms.

**Comment by snydergd** [comment]
@OrKoN Thanks for your patience. The part I'm confused of isn't related to the endpoints, but to availability of chromedriver artifacts for specific Chrome releases. If Chrome is released to my platform, should I be able to get a CfT chromedriver artifact for the same release on my platform?  Maybe I should be able to download it even if it's not in the "latest" or "known-good" lists?  Or maybe I can't.  I'm just hoping to find out so I know, and haven't seen the answer to that question called out anywhere.

**Comment by mathiasbynens** [comment]
@snydergd The use case you describe is currently not officially supported. Such downloads may or may not be available. 

To figure out the corresponding CfT ChromeDriver version for a given non-CfT Chrome binary, apply [Version Selection](https://chromedriver.chromium.org/downloads/version-selection) using the CfT JSON endpoints.
