### ISSUE TITLE
Will "known-good-versions-with-downloads.json" always grow in size?

### ISSUE THREAD

**Issue by alexsch01** [GoogleChromeLabs/chrome-for-testing#36]
Will the endpoint ```https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json``` always hold versions going back to 113?

I'm using this endpoint to find the download link for a specific version of Chromedriver since https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE#:~:text=We%20don%E2%80%99t%20have,downloads%60%20JSON%20endpoints.

**Comment by mathiasbynens** [comment]
Yes. If you’re worried about file size, you could use the flavor without downloads metadata instead: https://googlechromelabs.github.io/chrome-for-testing/known-good-versions.json And then construct the download URLs yourself based on the version number

**Comment by alexsch01** [comment]
Ok, I'll continue using the downloads JSON due to the raw download URLs possibility of changing in the future
