### ISSUE TITLE
Linux/ARM?

### ISSUE THREAD

**Issue by diemol** [GoogleChromeLabs/chrome-for-testing#37]
Hi folks, 

Is it on the roadmap to release a Linux/ARM binary?

Thank you,

**Comment by mathiasbynens** [comment]
See #1.

**Comment by diemol** [comment]
I guess I should follow good open source practices and read existing issue first 😆 
Thank you

**Comment by diemol** [comment]
The reason for this request is to have Docker Selenium containers that work for M1 and other ARM machines where Chrome is used instead of Chromium. 
https://github.com/seleniumhq-community/docker-seleniarm

**Comment by mathiasbynens** [comment]
Thank you for the additional context on your use case!
