### ISSUE TITLE
CfT reading from /chromium/policies instead of /chrome/policies on Linux

### ISSUE THREAD

**Issue by ladaflac** [GoogleChromeLabs/chrome-for-testing#39]
Hello!
Access to the application I am testing requires accepting a SSL certificate (in a corporate environment, Linux Mint). 
I have the **AutoSelectCertificateForUrls** rules (pattern) stored in a json file in **/etc/opt/chrome/policies**, which enables the standard Chrome to read from it and automatically accept the certificate, skipping the 'Select a certificate' popup. 
However, Chrome for Testing does not read the certificate policies from that location and I am getting the certificate popup. 
Workaround is to store the json file in **/etc/chromium/policies** - that way CfT will not be getting the cert popup. 
It doesn't seem right that CfT is reading from the chromium directory. Could it be a bug in CfT?

My environment:
Linux Mint 19.3
Chromium 112
Chrome 113
Chrome for Testing - tested with stable 114 and beta 116

**Comment by mathiasbynens** [comment]
Thanks for the report! I’ve filed this internally at https://bugs.chromium.org/p/chromium/issues/detail?id=1472226.

The design doc [explicitly states](https://docs.google.com/document/d/1XJvxyqAQjhPfJ0rX84PjfXXb5sBx3m8DXzMxR0ipQNs/edit#bookmark=id.28gjo3kyn4oy) that the Chrome for Testing MVP would follow Chromium policies, but that we should consider making it more similar to Chrome post-MVP. I suppose that time has come now :)

**Comment by ladaflac** [comment]
Sorry, I missed it in the design doc.
The change is not super urgent but it would reduce the confusion and save time to future users. Thanks for the feedback!

**Comment by thiagowfx** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1472226 is now fixed. Closing.

You cannot see the bug, but here's the commit for your reference: https://chromium-review.googlesource.com/c/chromium/src/+/4777118

**Comment by ladaflac** [comment]
I can confirm that the cert policies for CfT are now checked in /etc/opt/chrome. Tested on DEV v118.0.5993.3.
Thanks! :)
