### ISSUE TITLE
Getting following google API issue with Chrome-116.0.5845.97 and Selenium 4.11.0 which is blocking browser launch

### ISSUE THREAD

**Issue by Chetantn** [GoogleChromeLabs/chrome-for-testing#41]
1.   Today i have updated the chrome version to latest i.e **116.0.5845.97**  and i'm using selenium **4.11.0**  when i'm trying 
to launch the Chrome browser i'm getting following issue.

Error Logs for your reference: 
←[m13:59:45,961 ERROR [HttpClient] Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116
13:59:45,961 WARN  [VersionDetector] Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116 to get latest version of chromedriver (Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116)
←[37;41m2023-08-16 14:00:00,877 [ERROR] Failed to publish message com.smartbear.events.UpdateNavigatorTreeMessage@3b7fb962 to listener method com.smartbear.ready.ui.project.ServiceVModulePanel.handleUpdateModuleTreeMessage
←[m java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor304.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23) [mbassador-1.1.10.jar:?]
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49) [mbassador-1.1.10.jar:?]

==============================================================================
2.   Selenium is started using below command to make use of Selenium Manager 
    
java -jar selenium-server-4.11.0.jar standalone -p 4450 --session-timeout 620 **--selenium-manager true**

==============================================================================

3.   As i hit this below url i'm getting Latest available version as 114 only:

   https://chromedriver.storage.googleapis.com/LATEST_RELEASE 

  
![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/62075128/a12dad9b-28f6-419c-ac2a-013a5ddadc2a)

==============================================================================

4.   Also i can see selenium manager has downloaded required chrome driver in .cache, please refer below image 

![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/62075128/c792fe48-11d8-4878-8120-8a4e0cd5ce61)

Waiting for your response as we are blocked because of this issue

**Comment by laltamir** [comment]
Similar problem here:
the problem seems to be the resolution when the code is trying to find the LATEST version of Chromedriver. The workaround / patch to resolve this is to explicit define the version of chromedriver.
The change in our case is something like this:
wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip -O /tmp/chromedriver.zip
-  unzip 
- grant the permissions to execute in your code and call explicit this new download chromedriver  
- this is only a workaround so we are still waiting the solution with the LATEST for the chrome browser + chrome driver

**Comment by diemol** [comment]
You should report this to the Selenium project, this does not seem to be a CfT bug.

**Comment by Chetantn** [comment]
@diemol , ok i'll raise this issue with selenium project and update here. Thanks for your quick reply
