### ISSUE TITLE
It is unclear if chromedriver always matches the chrome version

### ISSUE THREAD

**Issue by pwspot** [GoogleChromeLabs/chrome-for-testing#48]
With chromedriver 114 and lower there was a dedicated URL to tell the latest chromedriver version:
https://chromedriver.storage.googleapis.com/LATEST_RELEASE

Here we have new links to tell the version, but it doesn't clearly specify if it is common for chrome and chromedriver:
https://github.com/GoogleChromeLabs/chrome-for-testing#other-api-endpoints

In https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json I can see that for Stable release there is a common version and I can assume that both chrome and chromedriver download links are based on that version.

Could you please confirm if it is safe to assume that the versions always match?
Nowhere in the docs it has been clearly stated.

**Comment by mathiasbynens** [comment]
> Here we have new links to tell the version, but it doesn't clearly specify if it is common for chrome and chromedriver:
> https://github.com/GoogleChromeLabs/chrome-for-testing#other-api-endpoints

From [the README](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints):

> The set of “all CfT assets” for a given Chrome version is a matrix of supported binaries × platforms.
>
> The current list of supported binaries is:
> 
> - `chrome` a.k.a. Chrome for Testing (supported since v113.0.5672.0)
> - `chromedriver` (supported since v115.0.5763.0)
> - `chrome-headless-shell` (supported since v118.0.5944.0)
> 
> The current list of supported platforms is:
> 
> - `linux64`
> - `mac-arm64`
> - `mac-x64`
> - `win32`
> - `win64`

Rest assured that any version number you obtain via the CfT JSON API or via the other endpoints are guaranteed to have all CfT assets available for that version.
