### ISSUE TITLE
Chrome Current stable URL link returns upcoming-Stable (116.0.5845.140) instead of Stable 116.0.5845.96

### ISSUE THREAD

**Issue by pravkum5** [GoogleChromeLabs/chrome-for-testing#49]
Issue : Returning wrong instable package (116.0.5845.140) in place of Stable 116.0.5845.96 chrome package .
Steps : 
Hit the link below and install package :
https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
Now install and verify the package 

Issue : 
It shows as 116.0.5845.140 .

Expected : 
It should be 116.0.5845.96 as the URLS for all 116.0.5845.140 returns 404 error .So linux package as stable should return **116.0.5845.96** only not as **116.0.5845.140**

chrome | linux64 |
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/linux64/chrome-linux64.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/mac-arm64/chrome-mac-arm64.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/mac-x64/chrome-mac-x64.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/win32/chrome-win32.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/win64/chrome-win64.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/linux64/chromedriver-linux64.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/mac-arm64/chromedriver-mac-arm64.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/mac-x64/chromedriver-mac-x64.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/win32/chromedriver-win32.zip | 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/win64/chromedriver-win64.zip

**Comment by mathiasbynens** [comment]
It sounds like you’re installing _regular_ non-CfT Chrome, and then you need to find a matching ChromeDriver binary. This version selection process is described here: https://chromedriver.chromium.org/downloads/version-selection

However, if feasible, it might be easier to stop using non-CfT Chrome for your testing use cases and instead install Chrome for Testing. That way you’re guaranteed to always have a matching Chrome for Testing + ChromeDriver binary with exactly the same version available.

Some extra background, in case interesting: https://chromiumdash.appspot.com/releases shows 116.0.5845.140 as being rolled out to 50%. Chrome for Testing currently only reliably gets 100% releases (but we’re working on that!). https://googlechromelabs.github.io/chrome-for-testing/ shows that 116.0.5845.140 is based on exactly the same revision as 116.0.5845.96, suggesting this could be an A/B test build.

**Comment by mj123237** [comment]
@mathiasbynens so question; we don't install chromium-browser, we install the official chrome binaries. I work with Praveen and we automate the install of latest chrome by the link he provided > https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb which is provided by google. If we do not intend to use chromium-browser which is essentially available by CfT, I guess we could run into incompatibility/availability of chromedriver, correct? In this case, google chrome latest is load 140 but chromedriver 140 is not available from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/.... yet, its upcoming and returns a 404 response code at the endpoint. So by checking the endpoint "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" I can see its still load 96.

**Comment by mathiasbynens** [comment]
If you want exactly the same versions for your Chrome and ChromeDriver binaries, then use Chrome for Testing. It allows you to pick any known good version and then download both binaries for that version for your platform.

If you insist on using a regular Chrome binary, then you need to follow the steps at https://chromedriver.chromium.org/downloads/version-selection to find the most compatible available ChromeDriver version.
