### ISSUE TITLE
Chrome for testing is only for automated testing bar on all screenshots

### ISSUE THREAD

**Issue by isparks-tg** [GoogleChromeLabs/chrome-for-testing#56]
Really appreciate the chance to fix to a chrome version for testing. The lack of this ability has been very difficult for us. We work in a regulated industry where we have extensive browser-based tests which take screenshots. These screenshots end up in validation documentation that is viewed by external auditors.

I'm noting when using a chrome-for-testing build:

![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/140390479/671608ef-fcc2-45c0-951d-fb908055644c)

A header that says "Chrome for testing vXXXX is only for automated testing...."

Well, yes. That's what we're doing, we are driving this with selenium. We don't need or want a header on every screenshot telling us so. Can we have a flag to turn this off?

**Comment by thiagowfx** [comment]
There's an internal-only FR for that: https://crbug.com/1476789 ("Re-introduce --disable-infobars as a CfT-only feature").

**Comment by thiagowfx** [comment]
This has now landed: https://chromium-review.googlesource.com/c/chromium/src/+/5012709

However, a release hasn't yet been made. Wait a few days and it should be available.
