### ISSUE TITLE
Chrome 117 --headless --disk-cache-dir segmentation fault

### ISSUE THREAD

**Issue by alexsch01** [GoogleChromeLabs/chrome-for-testing#57]
@mathiasbynens 

Cypress team found a bug in Chrome with the default headless mode in Chrome 117 stable: https://bugs.chromium.org/p/chromium/issues/detail?id=1483163

---

![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/5721147/0bcb77de-62b2-4a6a-bdd5-3f32f559fcff)

**Comment by thiagowfx** [comment]
Hi Alex, could you confirm if you're using Chrome for Testing, or is this Google Chrome? If the latter, then you should file a bug at crbug.com.
