### ISSUE TITLE
Cannot override "download.prompt_for_download" value if running on incognito mode

### ISSUE THREAD

**Issue by herickmota** [GoogleChromeLabs/chrome-for-testing#61]
From Chromedriver 117 and higher, if you need to download a file on incognito mode, the variable "download.prompt_for_download = False" on the chromeOptions is not not taken into account.

```
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument("--incognito")
    prefs = {
        "download.prompt_for_download": False,
    }
    chrome_options.add_experimental_option("prefs", prefs)
```

It turns out that with this configs the popup to save the file will always be prompted to the user.
If I remove the line`chrome_options.add_argument("--incognito")`, the setting is correctly taken into account and the popup is not prompted to the user.

**Comment by GCuser99** [comment]
Looks like one exists already...
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4578

**Comment by thiagowfx** [comment]
Thank you. Closing in favor of the aforementioned upstream bug.
