### ISSUE TITLE
Why are parts of safebrowsing still enabled after explicitly being disabled?

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/chrome-for-testing#62]
![Screenshot_2023-10-05_23-52-26](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/57626477-d1c3-454c-b6ea-254930c3e37a)
![Screenshot_2023-10-05_23-52-06](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/1ad0cd79-d144-4765-a447-0bcdb56cf922)

**Comment by thiagowfx** [comment]
Thank you for your report.

Does this also happen in regular Google Chrome, or is it specific to Chrome for Testing? If the former, then this would be the correct place to file a bug: https://bugs.chromium.org/p/chromium/issues/list

**Comment by guest271314** [comment]
I noticed it happening in CHromoum DevChannel, too. Unfortunately Chromium authors banned me from filing bugs on chromium.org.

If I don't want Google Safe Browsing on, I don't want it on. I explicitly turned it off. 

Not sure how to proceed with this given I can't file a bug under my user name and Google account.

**Comment by thiagowfx** [comment]
Closest to this I found upstream is https://bugs.chromium.org/p/chromium/issues/detail?id=1479834&q=%22safe%20browsing%22&can=2. It's related but I'm not sure if it's exactly the same issue.

If you believe it's not the same issue, I could file a bug on your behalf this time, but more information is needed. Here's the bug filing template in case you cannot see it as you don't have an account:

<img width="796" alt="image" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/2840106/9998ff0a-3f41-4f74-b1de-a613a017063e">

Just write a comment with some of these fields filled in and I'll relay it and link it here.

**Comment by guest271314** [comment]
Title: Google Safe Browsing is still enabled after I explicitly turn it off

(unless you cam come up with something better, even more explicit that I'm not interested in Google Safe Browsing, and I turned it off, don't want it on for testing, scanning downloads, whatever. I remember this happened before when I was experimening with File System Access API)

Chrome version: Version 119.0.6041.0 (Official Build) (64-bit) (Chrome-Fo-Testing). Also happens on Chromium Developer Build.

Steps to reproduce: Turn off Google Safe Browsing in Settings

Expected result: Google Safe Browsing to be **completely** off. No lingering "features" still turned on. No scanning of downloads, extension telemetry (what does that tracking have to do with Google Safe Browsing?). Assume the end-user knows what they are doing when they turn this off in Settings. I want this **off**, **disabled**, period.

What happens instead: Googel Safe Browsing is still enabled. - after I explicitly turned it off. (See attached images).

**Comment by guest271314** [comment]
Yes, it happens on Chrome (official), too.

**Comment by thiagowfx** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1490891.

**Comment by thiagowfx** [comment]
Unfortunately I don't have the capacity to proxy comments back-and-forth, I'd suggest asking them directly

**Comment by guest271314** [comment]
The Issue was closed, marked WontFix

[Comment 7](https://bugs.chromium.org/p/chromium/issues/detail?id=1490891#c7) by [drubery@chromium.org](https://bugs.chromium.org/u/644166437) on Tue, Oct 24, 2023, 9:13 AM PDT (5 days ago) Project MemberStatus: WontFix (was: Unconfirmed)
Owner: drubery@chromium.org

> I'd say this is WAI and close.

More erroneous, mixed messages on Chromium Version 120.0.6097.0 (Developer Build) (64-bit).

Here I deliberately turn off Google Safe Browsing in Settings (chrome://settings). Here the "Safety Check" says Google Safe Browsing is Enabled. 

Whose page is telling the truth and which page is lying?

![Screenshot_2023-10-29_19-23-25](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/f6d9b5cd-1a55-4bd8-82b2-5ad23a4488fe)
![Screenshot_2023-10-29_19-23-54](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/3f3a700d-fcd5-4a4c-83fc-44430254d678)
