### ISSUE TITLE
json api endpoints doesn't have checksum

### ISSUE THREAD

**Issue by dreagor** [GoogleChromeLabs/chrome-for-testing#63]
Hi everybody! i would like to know if there is the possibility to add checksum property to the json endpoints, since i have created a custom script in python to donwload the binaries but after unzipping chrome and chromedriver, chrome didn't start, after a couple of mins i said: if i donwload it manually? after unziping that one, it worked!

is that by design?

Saludos!

**Comment by mathiasbynens** [comment]
Could you share reproduction steps?

You seem to be describing a corrupted or incomplete download. In general, incomplete downloads aren’t even pushed to the buckets, so it’s unlikely that problem is fixable on our end.
