### ISSUE TITLE
The JSON API endpoint shows that the Beta channel version is newer than the Dev channel version

### ISSUE THREAD

**Issue by jsakamoto** [GoogleChromeLabs/chrome-for-testing#64]
Yesterday, 10/7/2023, I found that the JSON API endpoint (https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json) shows that the Beta channel version is newer than the Dev channel version.

![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/95908/554c0da1-bb80-4688-8ce1-9f4f216736e1)

Is that correct??

**Comment by thiagowfx** [comment]
Beta is definitely correct: https://chromereleases.googleblog.com/2023/10/chrome-beta-for-desktop-update_6.html

Dev should have been in 119 as well as per https://chromereleases.googleblog.com/2023/10/chrome-dev-for-desktop-update.html

**Comment by jsakamoto** [comment]
Thanks, @thiagowfx, for your reply!

Okay, but I still need clarification... Where has version 118 gone away?? Ver.118 doesn't exist in any channels.

**Comment by mathiasbynens** [comment]
The source of truth for Chrome (not CfT) releases is https://chromiumdash.appspot.com/releases.

CfT aims to follow that. In this case, https://googlechromelabs.github.io/chrome-for-testing/#dev shows that a CfT build was triggered across all platforms but the mac-x64 one hasn’t finished:

<img width="831" alt="image" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/81942/d1494b52-45a8-4484-8179-38e4786904e5">

**Comment by mathiasbynens** [comment]
On [the relevant build detail page](https://ci.chromium.org/ui/p/chrome/builders/official.cft/mac-x64-cft/1004/overview) (not public, sorry), it looks like step “27. compile” says “step was never finalized; did the build crash?”. I just manually restarted the build.

**Comment by jsakamoto** [comment]
@mathiasbynens 
When the entire build process is succeeded eventually, the versions of each channel will be the following, right?

- Stable ver.117
- Beta ver.119
- Dev ver.119
- Canary ver.120

If my understanding is correct, ver.118 will not be in any channels. Is that the expected result??

**Comment by mathiasbynens** [comment]
118 is going Stable this week, so this is expected.

**Comment by jsakamoto** [comment]
@mathiasbynens I could understand. Thank you for your reply.
