### ISSUE TITLE
No 117 Chrome Driver

### ISSUE THREAD

**Issue by SkyDuan** [GoogleChromeLabs/chrome-for-testing#65]
My Chrome version's 117 now but cannot find corresponding Driver, or update google Chrome to 118 either.

**Comment by mj123237** [comment]
You should be able to update your chrome version by navigating to Help -> About section on the right ••• hamburger column overlay. The current chrome version is 118x

**Comment by SkyDuan** [comment]
![Screen 'Capture](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/147787235/8d0c1e77-7ac0-4b8a-a459-683894196ecd)
There's no hamburger column in about section and it shows i've updated to latest version already.

**Comment by thiagowfx** [comment]
> My Chrome version's 117 now but cannot find corresponding Driver, or update google Chrome to 118 either.

If this is Chrome for Testing then this is working as intended, as it does not auto-update (see [doc](https://docs.google.com/document/d/1XJvxyqAQjhPfJ0rX84PjfXXb5sBx3m8DXzMxR0ipQNs/edit#bookmark=id.imv9vqowbun)).

If this is vanilla Google Chrome then unfortunately this is not the right forum. Use https://bugs.chromium.org/p/chromium/issues/entry?template=Defect+report+from+user instead.
