### ISSUE TITLE
how to use the python version of chrome for testing?

### ISSUE THREAD

**Issue by jecer** [GoogleChromeLabs/chrome-for-testing#67]
how to use the python version of chrome for testing?
I downloaded it, specified it in path (I had to rename it to chromedriver to make the system understand what I wanted), run the code in pycharm, the chrome for testing window opens, and that's it. even the link doesn't go through.
The error indicates that the Chrome driver cannot connect to the service. Windows platform

**Comment by mathiasbynens** [comment]
Chrome for Testing is the infrastructure that makes the binaries available. This repository specifically hosts the dashboard and the API endpoints.

There might be various tools that consume the CfT JSON endpoints and make it easy to download the various binaries (see https://developer.chrome.com/blog/chrome-for-testing/#how-can-i-get-chrome-for-testing-binaries) but any issues with those tools are outside the scope of this repository.
