### ISSUE TITLE
Serve .zip files with Access-Control-Allow-Origin: * header

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/chrome-for-testing#72]
I wrote some code to fetch the latest Canary version, unzip and write the folder to the local file system from the browser. The hinderance is `.zip` are not served with `Access-Control-Allow-Origin: *`  header.

```
Access to fetch at 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6081.0/linux64/chrome-linux64.zip' from origin 'https://www.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by guest271314** [comment]
This is a little more challenging than I initially suspected. I am able to get the `.zip` file using `window.open()`, extract the files and folders using JSZip() and writing the extracted folders and files to a directory using File System Access API, however, the executable permissions are not preserved.

**Comment by mathiasbynens** [comment]
I believe the approach of downloading the ZIP files via the browser would hit issues on macOS as well: https://github.com/GoogleChromeLabs/chrome-for-testing#macos-says-the-app-is-damaged-what-now

**Comment by guest271314** [comment]
I tested on Firefox Nightly 120 as well. Same non-executable files. I seriously suspect this has something to do with Google Safe Browsing, even though I deliberately turn that "feature" off on Chromium, Chrome-For-Testing, and Nightly. Fetching, extracting and reassembling works https://gist.github.com/guest271314/09733eaa2de16bd79f01d41de41ce843.

**Comment by guest271314** [comment]
@mathiasbynens There's no `c` or `r` option for the `xattr` I just installed on Linux.

**Comment by guest271314** [comment]
It would be uselful to test this using `fetch()` instead of `open()`.
