### ISSUE TITLE
Add linux-arm64 platform?

### ISSUE THREAD

**Issue by ats-aschwartz** [GoogleChromeLabs/chrome-for-testing#76]
> The current list of supported platforms is:
linux64
mac-arm64
mac-x64
win32
win64

Would it be possible to add linux-arm64 in addition to the linux64 (x86-64) version?

**Comment by thiagowfx** [comment]
Duplicate of: https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1#issuecomment-1537823171
