### ISSUE TITLE
New reduced user-agent

### ISSUE THREAD

**Issue by joseangel-mm** [GoogleChromeLabs/chrome-for-testing#8]
Hello all,

After reading about the new [reduced user-agent](https://developer.chrome.com/blog/user-agent-reduction-oct-2022-updates/), I wonder if in the following Google Chrome updates, the old user-agent will keep or it will be removed. 

Could you clarify this topic, please? 🙂

**Comment by mathiasbynens** [comment]
Unfortunately this is not a question about the code within this repository, so I’ll close it, but I hope you get your answer elsewhere. You might want to ask @ChromiumDev on Twitter.
