### ISSUE TITLE
"platform" definition uses ambigious and non-standard strings

### ISSUE THREAD

**Issue by dnmvisser** [GoogleChromeLabs/chrome-for-testing#85]
While scripting the download of a suitable chromedriver binary, I noticed an issue regarding the JSON that is returned from the API endpoints. For example [this one](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json), which contains items like:

```json
"chromedriver": [
  {
    "platform": "linux64",
    "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/linux64/chromedriver-linux64.zip"
  },
  {
    "platform": "mac-arm64",
    "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/mac-arm64/chromedriver-mac-arm64.zip"
  },
  {
    "platform": "mac-x64",
    "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/mac-x64/chromedriver-mac-x64.zip"
  },
  {
    "platform": "win32",
    "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/win32/chromedriver-win32.zip"
  },
  {
    "platform": "win64",
    "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/win64/chromedriver-win64.zip"
  }
],
```

Scripting this for mac and linux requires custom logic to accommodate the non-standard `platform` values, for example:

```shell
# Set reported platform
REPORTED_PLATFORM="$(uname -m)"

# Set platform for querying endpoints URL
# Ideally that URL would have just used the value reported by uname...
if [ "${REPORTED_PLATFORM}" == "arm64" ]; then
  PLATFORM="mac-arm64"
elif [ "${REPORTED_PLATFORM}" == "x86_64" ]; then
  PLATFORM="mac-x64"
else
  echo "Unsupported platform: ${REPORTED_PLATFORM}, exiting"
fi
```
etc etc

Why not use the same value as the OSes in question report themselves, for example though `uname`?

```shell
$ echo "$(uname -s)-$(uname -m)"
Linux-x86_64
```

```shell
$ echo "$(uname -s)-$(uname -m)"
Darwin-x86_64
```

```shell
$ echo "$(uname -s)-$(uname -m)"
Darwin-arm64
```

Meaning, if the JSON keys looked like this, scripting would be much easier:

```json
        "chromedriver": [
          {
            "platform": "Linux-x86_64",
            "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/linux64/chromedriver-linux64.zip"
          },
          {
            "platform": "Darwin-arm64",
            "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/mac-arm64/chromedriver-mac-arm64.zip"
          },
          {
            "platform": "Darwin-x86_64",
            "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/mac-x64/chromedriver-mac-x64.zip"
          },
          {
            "platform": "win32",
            "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/win32/chromedriver-win32.zip"
          },
          {
            "platform": "win64",
            "url": "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6124.0/win64/chromedriver-win64.zip"
          }
        ],
```

Also, it explicitly makes it clear that there are no `aarch86` builds for Linux....

**Comment by thiagowfx** [comment]
I'll answer the why: We named the builders/bots for CfT resembling the precedent of existing Chromium builders. Here is one example: https://crsrc.org/c/third_party/angle/testing/buildbot/waterfalls.pyl. You can find there things like "linux64", "arm64", and so on.

That said, we could take your report as a FR, so I'll leave this open for now.

**Comment by OrKoN** [comment]
I think we could add aliases to make the lookup easier. Although that would probably only work on Linux/MacOS. Windows might return things like `CYGWIN_NT-X` with uname so it would not match. WDYT? cc @mathiasbynens

**Comment by mathiasbynens** [comment]
Naming things is hard :)

Changing the builders + archive names + archive structure to slightly simplify scripting doesn’t seem worth it at this point. We’d have to add aliases for the “legacy” names anyhow to maintain backwards compatibility.

The list of supported platforms is captured in [the `README`](https://github.com/GoogleChromeLabs/chrome-for-testing#readme). Scripts already have to know about this list, since we don’t support every possible platform identifier that `uname` can output (and what you’re proposing might incorrectly create the impression that we do).

In your own scripts, it’s easy enough to create a mapping from the `uname` identifiers you wish to support to the platform labels we’re using. You kind of already have to do this anyway since you likely want to error or fall back to some default option when an unrecognized platform is used.
