### ISSUE TITLE
Way to simulate Manifest V2 deprecation

### ISSUE THREAD

**Issue by alexsch01** [GoogleChromeLabs/chrome-for-testing#87]
Is there a way to simulate Chrome Manifest V2 deprecation?

**Comment by guest271314** [comment]
What is the expected result?

**Comment by guest271314** [comment]
Chrome PDF Viewer is Manifest Version 2, among other extensions shipped with Chrome. See chrome://extension-internals

So is this

```
{
  "manifest_version": 2,
  "name": "Chrome Screen AI",
  "version": "121.3"
}
```

in  CfT Version 121.0.6167.0 (Official Build) (64-bit).

I don't see how Chrome is allegedly deprecating Manifest Version 2 for developers in the field yet shipping new internal extensions written using Manifest Version 2 without even describing what the code is doing in the extension manifest.

**Comment by alexsch01** [comment]
> What is the expected result?

I would expect the browser to still launch ok, just with the MV2 extensions no where to be found

**Comment by alexsch01** [comment]
@guest271314 

```
"manifest_version": 1,
   "name": "Web Store",
```
```
"manifest_version": 2,
   "name": "Google Docs Offline",
```
```
"manifest_version": 2,
   "name": "Chrome PDF Viewer",
```
```
"manifest_version": 2,
   "name": "Google Network Speech",
```
```
"manifest_version": 2,
   "name": "Google Hangouts",
```
```
"manifest_version": 2,
   "name": "Chrome Web Store Payments",
```

**Comment by alexsch01** [comment]
It just seems wrong to me to announce a depreciate date for MV2 extensions and there are still 4 preinstalled extensions that are still on MV2
- there are other extensions made by Google that are still on MV2 and not preinstalled

**Comment by mathiasbynens** [comment]
> [!IMPORTANT]
**This issue tracker tracks bugs with [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/) and [its API](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).**
> 
> - Are you reporting a bug that reproduces in Chrome for Testing but not in Chrome? File it here: https://goo.gle/cftbug
> - Are you reporting a bug in Chrome? File it here: https://crbug.com/new
