### ISSUE TITLE
Support pointing to the latest version URL

### ISSUE THREAD

**Issue by XHXIAIEIN** [GoogleChromeLabs/chrome-for-testing#94]
It is recommended to support channel paths to download the latest version of files.

For example, if I want to download the stable version chromedriver, the current URL is

chromedriver | win64 | 
```
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.71/win64/chromedriver-win64.zip
```

However, I hope that I can directly replace the version number with the path of a specific channel name to automatically access the latest version.

```
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/stable/win64/chromedriver-win64.zip
```

**Comment by mathiasbynens** [comment]
As you say, anyone could build this on top of the API endpoints quite easily.

Adding built-in support to the CDN for this is not planned, however. The current invariant is that all `*.zip` URLs we provide are “stable” i.e. always point to exactly the same file.
